# Generated by Django 4.0.4 on 2022-05-05 09:42

import Furniture.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('city', models.CharField(choices=[('S', 'Select'), ('M', 'Mumbai'), ('K', 'Kolkata'), ('B', 'Bengaluru'), ('G', 'Gujarat')], default='Select', max_length=20, validators=[Furniture.models.validate_city])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
