# Generated by Django 4.0.4 on 2022-05-13 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Furniture', '0002_buyerprofile_category_contactprofile_furnitureitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnitureitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Furniture.category'),
        ),
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Furniture.furnitureitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
