# Generated by Django 4.0.4 on 2022-05-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0005_rename_user_name_mycart_cart_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
