# Generated by Django 4.0.4 on 2022-05-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0006_mycart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
