# Generated by Django 4.0.4 on 2022-05-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0007_alter_mycart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='quantity_price',
            field=models.IntegerField(null=True),
        ),
    ]
