# Generated by Django 4.0.4 on 2022-05-18 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0009_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
    ]
