# Generated by Django 4.0.4 on 2022-05-18 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0010_remove_orderdetail_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Furniture.mycart', verbose_name='Product'),
        ),
    ]
